### ISSUE TITLE
String handling issues

### ISSUE THREAD

**Issue by xczsonn** [voky1/sims4-translator#2]
The translator has an issue with translating Korean to words within {} or missing { in some sentences.

![image](https://github.com/voky1/sims4-translator/assets/12751277/f3c8577d-ce80-4a71-8f87-3494dd4156bf)
![image](https://github.com/voky1/sims4-translator/assets/12751277/b2522037-4ba2-405a-88ed-aaef8357d435)

**Comment by Astercholik** [comment]
Texts {string}{money}{SimsName}{text|xxLower} etc. are not translated. Translation sites such as google/deepl do not know this.
And unfortunately you have to correct it yourself. You can only translate brackets containing
{M0.text}{M0.text} ect. This is a gender-specific translation.
